version: '3'

services:
  app:
    restart: unless-stopped
    container_name: receptori-server-container
    image: noah071610/receptori-server
    ports:
      - 5555:5555
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_PRODUCTION}
      REDIS_HOST: ${REDIS_HOST_PRODUCTION}
    depends_on:
      - mysql_db
      - redis
    networks:
      receptori_net:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      receptori_net:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      receptori_net:
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./conf/nginx.conf:/etc/nginx/nginx.conf
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     receptori_net:
  #   depends_on:
  #     - mysql_db
  #     - redis
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot

networks:
  receptori_net:
