import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.website.createMany({
    data: [
      {
        type: 'template',
        text: '',
        lang: 'ko',
        content: JSON.stringify([]),
      },
      {
        type: 'template',
        text: '',
        lang: 'en',
        content: JSON.stringify([]),
      },
      {
        type: 'template',
        text: '',
        lang: 'ja',
        content: JSON.stringify([]),
      },
      {
        type: 'template',
        text: '',
        lang: 'th',
        content: JSON.stringify([]),
      },
    ],
  });

  if (!process.env.IS_CLOUD_SERVER) {
    await prisma.user.createMany({
      data: [
        {
          userId: 'test',
          email: process.env.ADMIN_EMAIL,
          userImage:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp5eN0cagenqe3YRME3noqb6X74pDSq0rw8g&s',
          userName: 'Noah',
          provider: 'google',
          color: 'rgba(117, 130, 253, 1)',
          plan: 2,
        },
      ],
    });

    await prisma.save.createMany({
      data: [
        {
          title: '리셉토리',
          description: '안녕 리셉토리',
          format: 'active',
          lang: 'ko',
          pageId: 'test',
          userId: 'test',
          customLink: 'receptori',
          content: JSON.stringify({
            stage: 'rending',
            homeSections: [
              {
                id: 'thumbnail',
                index: 0,
                type: 'thumbnail',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                  cta: '폼으로 이동',
                },
                collection: [],
                list: [],
                style: {
                  src: '',
                  color: 'rgba(14, 32, 196, 0.5)',
                  background: '',
                  backgroundColor: 'rgba(14, 32, 196, 0.5)',
                },
                options: {},
                design: 'simple',
                src: '',
                text: '',
              },
            ],
            formSections: [
              {
                id: 'formThumbnail',
                index: 0,
                type: 'thumbnail',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                  cta: '폼으로 이동',
                },
                collection: [],
                list: [],
                style: {
                  src: '',
                  color: 'rgba(14, 32, 196, 0.5)',
                  background: '',
                  backgroundColor: 'rgba(14, 32, 196, 0.5)',
                },
                options: {},
                design: 'background',
                src: '',
                text: '',
              },
              {
                id: 'hD4t5Dtlv36p',
                index: 1,
                type: 'calendar',
                value: '',
                isActive: false,
                data: {
                  title: '기간은 언제로',
                  description: '',
                },
                collection: [],
                list: [],
                style: {},
                options: {
                  isAlways: true,
                  specificDate: false,
                  addAnyDate: false,
                  interval: 'all',
                  isRangeSelect: false,
                  selectedSpecificDates: [],
                },
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'YhWlfqQtB3u6',
                index: 2,
                type: 'time',
                value: '',
                isActive: false,
                data: {
                  title: '시간 입력',
                  description: '설명 입력',
                },
                collection: [],
                list: [],
                style: {},
                options: {
                  isAlways: true,
                  specificTime: false,
                  addAnytime: false,
                  interval: '1',
                  startHour: '00',
                  endHour: '00',
                  isRangeSelect: false,
                  selectedSpecificTimes: [],
                },
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'rWZ8HB81hSzz',
                index: 3,
                type: 'select',
                isActive: false,
                data: {
                  title: '골라봐요',
                  description: '설명 입력',
                },
                collection: [],
                list: [
                  {
                    id: 'i6-go0XkKVvC',
                    index: 0,
                    type: 'select',
                    value: '',
                    isActive: false,
                    data: {
                      title: '1번 맛집',
                      description: '',
                    },
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                  {
                    id: 'i6-go0XkKVAC',
                    index: 1,
                    type: 'select',
                    value: '',
                    isActive: false,
                    data: {
                      title: '2번 형님집',
                      description: '',
                    },
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                ],
                style: {},
                options: {
                  isMultiple: false,
                  addSelectNone: false,
                },
                design: 'imageWithText',
                src: '',
                text: '',
              },
              {
                id: '8gzcMZ2UYk6Z',
                index: 4,
                type: 'choices',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                },
                collection: [],
                list: [
                  {
                    id: 'eX9T9AY-mXcQ',
                    index: 0,
                    type: 'left',
                    value: '남성',
                    isActive: false,
                    data: {},
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                  {
                    id: 'FiOk8xnp5ieL',
                    index: 1,
                    type: 'right',
                    value: '여성',
                    isActive: false,
                    data: {},
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                ],
                style: {},
                options: {},
                design: 'gender',
                src: '',
                text: '',
              },
              {
                id: 'hlf4KNEchOcy',
                index: 5,
                type: 'nameInput',
                value: '',
                isActive: false,
                data: {
                  title: '이름이 뭐에요?',
                  description: '알려줘요',
                },
                collection: [],
                list: [],
                style: {},
                options: {},
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'XoZHjYSw0Rv2',
                index: 6,
                type: 'email',
                value: '',
                isActive: false,
                data: {
                  title: '이메일 입력토리',
                  description: '',
                },
                collection: [],
                list: [],
                style: {},
                options: {},
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'KX6ONoibCqMl',
                index: 7,
                type: 'phone',
                value: '',
                isActive: false,
                data: {
                  title: '전화번호 뭐에요',
                  description: '뭡니까',
                },
                collection: [],
                list: [],
                style: {},
                options: {
                  phoneNumberCountry: 'ko',
                },
                design: 'basic',
                src: '',
                text: '',
              },
            ],
            confirmSections: [
              {
                id: 'rendingThumbnail',
                index: 0,
                type: 'thumbnail',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                  cta: '폼으로 이동',
                },
                collection: [],
                list: [],
                style: {
                  src: '',
                  color: 'rgba(14, 32, 196, 0.5)',
                  background: '',
                  backgroundColor: 'rgba(14, 32, 196, 0.5)',
                },
                options: {},
                design: 'background',
                src: '',
                text: '',
              },
              {
                id: 'confirm',
                index: 1,
                type: 'confirm',
                value: '',
                isActive: false,
                data: {
                  title: '토리토리! 감사합니다.',
                  description: '귀한 시간 내주셔서 감사합니다토리.',
                },
                collection: [],
                list: [],
                style: {},
                options: {},
                design: 'basic',
                src: '',
                text: '',
              },
            ],
            currentUsedImages: [],
            currentUsedColors: [],
            pageOptions: {
              format: 'active',
              lang: 'ko',
              isUseHomeThumbnail: false,
              isNotUseCustomLink: false,
              customLink: 'receptori',
              embed: {
                title: '리셉토리 플랜 업그레이드 신청 페이지',
                description: '나만의 멋진 홈페이지가 단돈 커피 한 잔 값',
                src: 'https://newsimg-hams.hankookilbo.com/2024/01/01/0420a9b9-b79a-42f1-a2a8-0d549121ff72.jpg',
              },
            },
          }),
          thumbnail:
            'https://media.istockphoto.com/id/133909981/ko/%EC%82%AC%EC%A7%84/%EB%82%9C%EC%9F%81%EC%9D%B4-%ED%96%84%EC%8A%A4%ED%84%B0.jpg?s=612x612&w=0&k=20&c=K4CtbCandVmwF47gDhYAljUvMy9LHH21Z1-UZMzgguY=',
          createdAt: new Date(),
        },
      ],
    });

    await prisma.page.createMany({
      data: [
        {
          title: '리셉토리',
          description: '안녕 리셉토리',
          format: 'active',
          lang: 'ko',
          pageId: 'test',
          userId: 'test',
          customLink: 'receptori',
          createdAt: new Date(),
          thumbnail:
            'https://media.istockphoto.com/id/133909981/ko/%EC%82%AC%EC%A7%84/%EB%82%9C%EC%9F%81%EC%9D%B4-%ED%96%84%EC%8A%A4%ED%84%B0.jpg?s=612x612&w=0&k=20&c=K4CtbCandVmwF47gDhYAljUvMy9LHH21Z1-UZMzgguY=',
          analyser: JSON.stringify({
            submit: {
              anyDate: 0,
              map: {},
            },
            calendar: {
              anyDate: 0,
              map: {},
            },
            time: {
              anytime: 0,
              map: {
                AM: Array.from({ length: 12 }, () => 0),
                PM: Array.from({ length: 12 }, () => 0),
              },
            },
            select: {},
            choices: {},
          }),
          content: JSON.stringify({
            homeSections: [
              {
                id: 'thumbnail',
                index: 0,
                type: 'thumbnail',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                  cta: '폼으로 이동',
                },
                collection: [],
                list: [],
                style: {
                  src: '',
                  color: 'rgba(14, 32, 196, 0.5)',
                  background: '',
                  backgroundColor: 'rgba(14, 32, 196, 0.5)',
                },
                options: {},
                design: 'simple',
                src: '',
                text: '',
              },
            ],
            formSections: [
              {
                id: 'formThumbnail',
                index: 0,
                type: 'thumbnail',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                  cta: '폼으로 이동',
                },
                collection: [],
                list: [],
                style: {
                  src: '',
                  color: 'rgba(14, 32, 196, 0.5)',
                  background: '',
                  backgroundColor: 'rgba(14, 32, 196, 0.5)',
                },
                options: {},
                design: 'background',
                src: '',
                text: '',
              },
              {
                id: 'hD4t5Dtlv36p',
                index: 1,
                type: 'calendar',
                value: '',
                isActive: false,
                data: {
                  title: '기간은 언제로',
                  description: '',
                },
                collection: [],
                list: [],
                style: {},
                options: {
                  isAlways: true,
                  specificDate: false,
                  addAnyDate: false,
                  interval: 'all',
                  isRangeSelect: false,
                  selectedSpecificDates: [],
                },
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'YhWlfqQtB3u6',
                index: 2,
                type: 'time',
                value: '',
                isActive: false,
                data: {
                  title: '시간 입력',
                  description: '설명 입력',
                },
                collection: [],
                list: [],
                style: {},
                options: {
                  isAlways: true,
                  specificTime: false,
                  addAnytime: false,
                  interval: '1',
                  startHour: '00',
                  endHour: '00',
                  isRangeSelect: false,
                  selectedSpecificTimes: [],
                },
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'rWZ8HB81hSzz',
                index: 3,
                type: 'select',
                isActive: false,
                data: {
                  title: '골라봐요',
                  description: '설명 입력',
                },
                collection: [],
                list: [
                  {
                    id: 'i6-go0XkKVvC',
                    index: 0,
                    type: 'select',
                    value: '',
                    isActive: false,
                    data: {
                      title: '1번 맛집',
                      description: '',
                    },
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                  {
                    id: 'i6-go0XkKVAC',
                    index: 1,
                    type: 'select',
                    value: '',
                    isActive: false,
                    data: {
                      title: '2번 형님집',
                      description: '',
                    },
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                ],
                style: {},
                options: {
                  isMultiple: false,
                  addSelectNone: false,
                },
                design: 'imageWithText',
                src: '',
                text: '',
              },
              {
                id: '8gzcMZ2UYk6Z',
                index: 4,
                type: 'choices',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                },
                collection: [],
                list: [
                  {
                    id: 'eX9T9AY-mXcQ',
                    index: 0,
                    type: 'left',
                    value: '남성',
                    isActive: false,
                    data: {},
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                  {
                    id: 'FiOk8xnp5ieL',
                    index: 1,
                    type: 'right',
                    value: '여성',
                    isActive: false,
                    data: {},
                    collection: [],
                    list: [],
                    style: {},
                    options: {},
                    design: 'basic',
                    src: '',
                    text: '',
                  },
                ],
                style: {},
                options: {},
                design: 'gender',
                src: '',
                text: '',
              },
              {
                id: 'hlf4KNEchOcy',
                index: 5,
                type: 'nameInput',
                value: '',
                isActive: false,
                data: {
                  title: '이름이 뭐에요?',
                  description: '알려줘요',
                },
                collection: [],
                list: [],
                style: {},
                options: {},
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'XoZHjYSw0Rv2',
                index: 6,
                type: 'email',
                value: '',
                isActive: false,
                data: {
                  title: '이메일 입력토리',
                  description: '',
                },
                collection: [],
                list: [],
                style: {},
                options: {},
                design: 'basic',
                src: '',
                text: '',
              },
              {
                id: 'KX6ONoibCqMl',
                index: 7,
                type: 'phone',
                value: '',
                isActive: false,
                data: {
                  title: '전화번호 뭐에요',
                  description: '뭡니까',
                },
                collection: [],
                list: [],
                style: {},
                options: {
                  phoneNumberCountry: 'ko',
                },
                design: 'basic',
                src: '',
                text: '',
              },
            ],
            confirmSections: [
              {
                id: 'rendingThumbnail',
                index: 0,
                type: 'thumbnail',
                value: '',
                isActive: false,
                data: {
                  title: '타이틀 입력',
                  description: '설명 입력',
                  cta: '폼으로 이동',
                },
                collection: [],
                list: [],
                style: {
                  src: '',
                  color: 'rgba(14, 32, 196, 0.5)',
                  background: '',
                  backgroundColor: 'rgba(14, 32, 196, 0.5)',
                },
                options: {},
                design: 'background',
                src: '',
                text: '',
              },
              {
                id: 'confirm',
                index: 1,
                type: 'confirm',
                value: '',
                isActive: false,
                data: {
                  title: '토리토리! 감사합니다.',
                  description: '귀한 시간 내주셔서 감사합니다토리.',
                },
                collection: [],
                list: [],
                style: {},
                options: {},
                design: 'basic',
                src: '',
                text: '',
              },
            ],
            pageOptions: {
              format: 'active',
              lang: 'ko',
              isUseHomeThumbnail: false,
              isNotUseCustomLink: false,
              customLink: 'receptori',
              embed: {
                title: '리셉토리 플랜 업그레이드 신청 페이지',
                description: '나만의 멋진 홈페이지가 단돈 커피 한 잔 값',
                src: 'https://newsimg-hams.hankookilbo.com/2024/01/01/0420a9b9-b79a-42f1-a2a8-0d549121ff72.jpg',
              },
            },
          }),
        },
      ],
    });
  }

  await prisma.$disconnect();
}

main().catch((error) => {
  throw error;
});
