name: Docker ec2 CD

on:
  workflow_run:
    workflows: ['Docker Image CI']
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted, label-go]

    steps:
      - name: Docker remove image
        run: |
          sudo docker compose stop app || true
          sudo docker rm receptori-server-container || true
          sudo docker rmi noah071610/receptori-server:latest || true

      - name: Docker pull
        run: |
          sudo docker pull noah071610/receptori-server:latest
          sudo docker compose up -d --build app
